"""core schema

Revision ID: 10765f663942
Revises: 
Create Date: 2026-08-20 08:26:15.000213
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '10765f663942'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('organization_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name=op.f('ck_organization_members_role_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_members_organization_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_organization_members_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_members')),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_members_org_user')
    )
    op.create_index('ix_organization_members_user', 'organization_members', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('id', 'organization_id', name='uq_projects_id_organization_id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_projects_org_slug')
    )
    op.create_table('refresh_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti', name=op.f('pk_refresh_tokens'))
    )
    op.create_index('ix_refresh_tokens_user_active', 'refresh_tokens', ['user_id'], unique=False, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_table('retry_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strategy', sa.String(length=20), nullable=False),
    sa.Column('base_ms', sa.Integer(), nullable=False),
    sa.Column('max_ms', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("strategy IN ('fixed', 'linear', 'exponential')", name=op.f('ck_retry_policies_strategy_valid')),
    sa.CheckConstraint('base_ms BETWEEN 1 AND 3600000', name=op.f('ck_retry_policies_base_ms_range')),
    sa.CheckConstraint('max_attempts BETWEEN 1 AND 50', name=op.f('ck_retry_policies_max_attempts_range')),
    sa.CheckConstraint('max_ms >= base_ms', name=op.f('ck_retry_policies_max_ms_gte_base')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_retry_policies_organization_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retry_policies')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_retry_policies_org_name')
    )
    op.create_table('queues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('default_priority', sa.SmallInteger(), nullable=False),
    sa.Column('visibility_timeout_sec', sa.Integer(), nullable=False),
    sa.Column('default_timeout_ms', sa.Integer(), nullable=False),
    sa.Column('max_payload_bytes', sa.Integer(), nullable=False),
    sa.Column('retry_policy_id', sa.Uuid(), nullable=True),
    sa.Column('dlq_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_paused', sa.Boolean(), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_retention_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('default_priority BETWEEN -100 AND 100', name=op.f('ck_queues_default_priority_range')),
    sa.CheckConstraint('default_timeout_ms < visibility_timeout_sec * 1000', name=op.f('ck_queues_timeout_lt_lease')),
    sa.CheckConstraint('is_paused = (paused_at IS NOT NULL)', name=op.f('ck_queues_pause_consistency')),
    sa.CheckConstraint('max_concurrency BETWEEN 1 AND 1000', name=op.f('ck_queues_max_concurrency_range')),
    sa.CheckConstraint('max_payload_bytes BETWEEN 1024 AND 1048576', name=op.f('ck_queues_payload_range')),
    sa.CheckConstraint('priority BETWEEN -100 AND 100', name=op.f('ck_queues_priority_range')),
    sa.CheckConstraint('visibility_timeout_sec BETWEEN 10 AND 3600', name=op.f('ck_queues_visibility_range')),
    sa.ForeignKeyConstraint(['project_id', 'organization_id'], ['projects.id', 'projects.organization_id'], name='fk_queues_project', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['retry_policy_id'], ['retry_policies.id'], name=op.f('fk_queues_retry_policy_id'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_queues')),
    sa.UniqueConstraint('id', 'organization_id', name='uq_queues_id_organization_id'),
    sa.UniqueConstraint('id', 'project_id', name='uq_queues_id_project_id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_queues_project_name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('schedule_id', sa.Uuid(), nullable=True),
    sa.Column('replay_of_job_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('handler', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'queued', 'claimed', 'running', 'completed', 'failed', 'dead_letter', 'cancelled', name='job_status'), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('backoff_strategy', sa.String(length=20), nullable=False),
    sa.Column('backoff_base_ms', sa.Integer(), nullable=False),
    sa.Column('backoff_max_ms', sa.Integer(), nullable=False),
    sa.Column('unregistered_count', sa.Integer(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('lease_seconds', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('lease_epoch', sa.BigInteger(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('last_error_class', sa.String(length=200), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status IN ('cancelled', 'completed', 'dead_letter', 'failed')) = (finished_at IS NOT NULL)", name=op.f('ck_jobs_terminal_finished')),
    sa.CheckConstraint("backoff_strategy IN ('fixed', 'linear', 'exponential')", name=op.f('ck_jobs_backoff_strategy_valid')),
    sa.CheckConstraint("kind <> 'recurring' OR schedule_id IS NOT NULL", name=op.f('ck_jobs_recurring_needs_schedule')),
    sa.CheckConstraint("kind IN ('immediate', 'delayed', 'scheduled', 'recurring', 'batch')", name=op.f('ck_jobs_kind_valid')),
    sa.CheckConstraint("status NOT IN ('claimed', 'running') OR (lease_expires_at IS NOT NULL AND claimed_at IS NOT NULL)", name=op.f('ck_jobs_lease_present')),
    sa.CheckConstraint('(schedule_id IS NULL) = (scheduled_for IS NULL)', name=op.f('ck_jobs_schedule_occurrence')),
    sa.CheckConstraint('attempt >= 0', name=op.f('ck_jobs_attempt_non_negative')),
    sa.CheckConstraint('max_attempts BETWEEN 1 AND 50', name=op.f('ck_jobs_max_attempts_range')),
    sa.CheckConstraint('pg_column_size(payload) <= 1048576', name=op.f('ck_jobs_payload_size')),
    sa.CheckConstraint('priority BETWEEN -100 AND 100', name=op.f('ck_jobs_priority_range')),
    sa.CheckConstraint('timeout_ms < lease_seconds * 1000', name=op.f('ck_jobs_timeout_lt_lease')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_jobs_organization_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id', 'project_id'], ['queues.id', 'queues.project_id'], name='fk_jobs_queue', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replay_of_job_id'], ['jobs.id'], name=op.f('fk_jobs_replay_of_job_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('id', 'organization_id', name='uq_jobs_id_organization_id')
    )
    op.create_index('ix_jobs_batch', 'jobs', ['batch_id', 'status'], unique=False, postgresql_where=sa.text('batch_id IS NOT NULL'))
    op.create_index('ix_jobs_claim', 'jobs', ['queue_id', sa.literal_column('priority DESC'), sa.literal_column('run_at ASC'), 'id'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index('ix_jobs_depth', 'jobs', ['queue_id', 'status'], unique=False, postgresql_where=sa.text("status IN ('claimed', 'queued', 'running', 'scheduled')"))
    op.create_index('ix_jobs_due', 'jobs', ['run_at'], unique=False, postgresql_where=sa.text("status = 'scheduled'"))
    op.create_index('ix_jobs_lease', 'jobs', ['lease_expires_at'], unique=False, postgresql_where=sa.text("status IN ('claimed', 'running')"))
    op.create_index('ix_jobs_project_created', 'jobs', ['project_id', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ix_jobs_queue_status_created', 'jobs', ['queue_id', 'status', sa.literal_column('created_at DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ux_jobs_live_idempotency', 'jobs', ['queue_id', 'idempotency_key'], unique=True, postgresql_where=sa.text("idempotency_key IS NOT NULL AND status IN ('claimed', 'queued', 'running', 'scheduled')"))
    op.create_index('ux_jobs_schedule_occurrence', 'jobs', ['schedule_id', 'scheduled_for'], unique=True, postgresql_where=sa.text('schedule_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_jobs_schedule_occurrence', table_name='jobs', postgresql_where=sa.text('schedule_id IS NOT NULL'))
    op.drop_index('ux_jobs_live_idempotency', table_name='jobs', postgresql_where=sa.text("idempotency_key IS NOT NULL AND status IN ('claimed', 'queued', 'running', 'scheduled')"))
    op.drop_index('ix_jobs_queue_status_created', table_name='jobs')
    op.drop_index('ix_jobs_project_created', table_name='jobs')
    op.drop_index('ix_jobs_lease', table_name='jobs', postgresql_where=sa.text("status IN ('claimed', 'running')"))
    op.drop_index('ix_jobs_due', table_name='jobs', postgresql_where=sa.text("status = 'scheduled'"))
    op.drop_index('ix_jobs_depth', table_name='jobs', postgresql_where=sa.text("status IN ('claimed', 'queued', 'running', 'scheduled')"))
    op.drop_index('ix_jobs_claim', table_name='jobs', postgresql_where=sa.text("status = 'queued'"))
    op.drop_index('ix_jobs_batch', table_name='jobs', postgresql_where=sa.text('batch_id IS NOT NULL'))
    op.drop_table('jobs')
    op.drop_table('queues')
    op.drop_table('retry_policies')
    op.drop_index('ix_refresh_tokens_user_active', table_name='refresh_tokens', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_table('refresh_tokens')
    op.drop_table('projects')
    op.drop_index('ix_organization_members_user', table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
    # Alembic autogenerate never emits DROP TYPE for native enums. Without this the
    # type survives `downgrade base`, and the next `upgrade head` fails with
    # DuplicateObjectError: type "job_status" already exists.
    # Regression-covered by tests/test_migrations.py::test_upgrade_downgrade_roundtrip.
    sa.Enum(name="job_status").drop(op.get_bind(), checkfirst=True)
