"""fix frozen refresh_tokens created_at default

Revision ID: 484e1c2dbe89
Revises: f8ef4aba8de3
Create Date: 2026-08-20 09:23:50.341191
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '484e1c2dbe89'
down_revision: str | None = 'f8ef4aba8de3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Unfreeze refresh_tokens.created_at.

    server_default="now()" was passed as a plain Python string, so SQLAlchemy
    emitted it as a LITERAL: Postgres evaluated now() once at DDL time and froze
    that constant as the column default. Every row would have carried the
    timestamp of the migration rather than its own creation time. text("now()")
    emits the function call instead.

    compare_server_default=True in alembic/env.py is what makes this class of
    drift visible to `alembic check`.
    """
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-08-20 08:27:47.239786+05:30'::timestamp with time zone"),
               existing_nullable=False)
    # ### end Alembic commands ###
