"""workers and executions

Revision ID: eafcffd66e0b
Revises: 10765f663942
Create Date: 2026-08-20 08:38:39.115351
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'eafcffd66e0b'
down_revision: str | None = '10765f663942'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('drain_requested', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('starting', 'active', 'draining', 'stopped', 'dead')", name=op.f('ck_workers_status_valid')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_workers_organization_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_workers_org_name')
    )
    op.create_index('ix_workers_liveness', 'workers', ['organization_id', 'last_heartbeat_at'], unique=False)
    op.create_table('worker_heartbeats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=False),
    sa.Column('beat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inflight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_worker_heartbeats_worker_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_heartbeats'))
    )
    op.create_index('ix_worker_heartbeats_worker_time', 'worker_heartbeats', ['worker_id', sa.literal_column('beat_at DESC')], unique=False)
    op.create_table('job_executions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Uuid(), nullable=True),
    sa.Column('lease_epoch', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('claimed', 'running', 'succeeded', 'failed', 'timed_out', 'cancelled', 'lost', name='execution_status'), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('queue_wait_ms', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_class', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('log_line_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("(status IN ('claimed', 'running')) = (finished_at IS NULL)", name=op.f('ck_job_executions_open_iff_unfinished')),
    sa.ForeignKeyConstraint(['job_id', 'organization_id'], ['jobs.id', 'jobs.organization_id'], name='fk_job_executions_job', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_job_executions_worker_id'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_executions'))
    )
    op.create_index('ix_job_executions_job', 'job_executions', ['job_id', sa.literal_column('attempt_number DESC'), sa.literal_column('id DESC')], unique=False)
    op.create_index('ux_job_executions_open_one', 'job_executions', ['job_id'], unique=True, postgresql_where=sa.text('finished_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_job_executions_open_one', table_name='job_executions', postgresql_where=sa.text('finished_at IS NULL'))
    op.drop_index('ix_job_executions_job', table_name='job_executions')
    op.drop_table('job_executions')
    op.drop_index('ix_worker_heartbeats_worker_time', table_name='worker_heartbeats')
    op.drop_table('worker_heartbeats')
    op.drop_index('ix_workers_liveness', table_name='workers')
    op.drop_table('workers')
    # ### end Alembic commands ###
    # See the core-schema migration: autogenerate never emits DROP TYPE for native
    # enums, so without this the second `upgrade head` fails with DuplicateObject.
    sa.Enum(name="execution_status").drop(op.get_bind(), checkfirst=True)
