"""scheduling, dlq, logs, observability

Revision ID: eb052146b351
Revises: 484e1c2dbe89
Create Date: 2026-08-20 12:56:28.237786
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'eb052146b351'
down_revision: str | None = '484e1c2dbe89'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_state',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_system_state'))
    )
    op.create_table('job_batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('handler', sa.String(length=200), nullable=False),
    sa.Column('total_jobs', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('total_jobs BETWEEN 1 AND 1000', name=op.f('ck_job_batches_total_jobs_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_job_batches_organization_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id', 'project_id'], ['queues.id', 'queues.project_id'], name='fk_job_batches_queue', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_batches'))
    )
    op.create_index('ix_job_batches_project_created', 'job_batches', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('job_schedules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cron', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('next_occurrence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_occurrence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('catchup_policy', sa.String(length=20), server_default=sa.text("'skip'"), nullable=False),
    sa.Column('max_catchup_occurrences', sa.Integer(), server_default=sa.text('10'), nullable=False),
    sa.Column('skipped_occurrences', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('handler', sa.String(length=200), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('priority', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), server_default=sa.text('60000'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("catchup_policy IN ('skip', 'catchup')", name=op.f('ck_job_schedules_catchup_policy_valid')),
    sa.CheckConstraint('max_attempts BETWEEN 1 AND 50', name=op.f('ck_job_schedules_max_attempts_range')),
    sa.CheckConstraint('max_catchup_occurrences BETWEEN 1 AND 1000', name=op.f('ck_job_schedules_max_catchup_range')),
    sa.CheckConstraint('priority BETWEEN -100 AND 100', name=op.f('ck_job_schedules_priority_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_job_schedules_organization_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['queue_id', 'project_id'], ['queues.id', 'queues.project_id'], name='fk_job_schedules_queue', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_schedules'))
    )
    op.create_index('ix_job_schedules_due', 'job_schedules', ['next_occurrence_at'], unique=False, postgresql_where=sa.text('is_active AND deleted_at IS NULL'))
    op.create_index('ux_job_schedules_queue_name', 'job_schedules', ['queue_id', 'name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('queue_stats_minute',
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enqueued', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('completed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('failed', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dead_lettered', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('retried', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sum_duration_ms', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('max_duration_ms', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("date_trunc('minute', bucket_start) = bucket_start", name=op.f('ck_queue_stats_minute_bucket_aligned')),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], name='fk_queue_stats_minute_queue', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('queue_id', 'bucket_start', name=op.f('pk_queue_stats_minute'))
    )
    op.create_index('ix_queue_stats_minute_bucket', 'queue_stats_minute', [sa.literal_column('bucket_start DESC')], unique=False)
    op.create_table('dead_letter_entries',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('queue_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('error_class', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_fingerprint', sa.String(length=32), nullable=True),
    sa.Column('payload_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolution', sa.String(length=20), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('replay_job_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("resolution IS NULL OR resolution IN ('requeued', 'discarded', 'resolved_manually')", name=op.f('ck_dead_letter_entries_resolution_valid')),
    sa.CheckConstraint('(resolution IS NULL) = (resolved_at IS NULL)', name=op.f('ck_dead_letter_entries_resolution_closed')),
    sa.ForeignKeyConstraint(['job_id', 'organization_id'], ['jobs.id', 'jobs.organization_id'], name='fk_dead_letter_entries_job', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replay_job_id'], ['jobs.id'], name=op.f('fk_dead_letter_entries_replay_job_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_dead_letter_entries_resolved_by'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dead_letter_entries'))
    )
    op.create_index('ix_dlq_open', 'dead_letter_entries', ['project_id', sa.literal_column('dead_lettered_at DESC')], unique=False, postgresql_where=sa.text('resolution IS NULL'))
    op.create_table('job_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('execution_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), server_default=sa.text("'info'"), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IN ('debug', 'info', 'warning', 'error', 'critical')", name=op.f('ck_job_logs_level_valid')),
    sa.CheckConstraint('seq >= 0', name=op.f('ck_job_logs_seq_non_negative')),
    sa.ForeignKeyConstraint(['execution_id'], ['job_executions.id'], name=op.f('fk_job_logs_execution_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_logs_job_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_logs')),
    sa.UniqueConstraint('execution_id', 'seq', name='uq_job_logs_execution_id_seq')
    )
    op.create_foreign_key(op.f('fk_jobs_schedule_id'), 'jobs', 'job_schedules', ['schedule_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_jobs_batch_id'), 'jobs', 'job_batches', ['batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_jobs_batch_id'), 'jobs', type_='foreignkey')
    op.drop_constraint(op.f('fk_jobs_schedule_id'), 'jobs', type_='foreignkey')
    op.drop_table('job_logs')
    op.drop_index('ix_dlq_open', table_name='dead_letter_entries', postgresql_where=sa.text('resolution IS NULL'))
    op.drop_table('dead_letter_entries')
    op.drop_index('ix_queue_stats_minute_bucket', table_name='queue_stats_minute')
    op.drop_table('queue_stats_minute')
    op.drop_index('ux_job_schedules_queue_name', table_name='job_schedules', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_job_schedules_due', table_name='job_schedules', postgresql_where=sa.text('is_active AND deleted_at IS NULL'))
    op.drop_table('job_schedules')
    op.drop_index('ix_job_batches_project_created', table_name='job_batches')
    op.drop_table('job_batches')
    op.drop_table('system_state')
    # ### end Alembic commands ###
    # No sa.Enum(...).drop() here on purpose: every new type in this migration is
    # TEXT + CHECK, not a native enum. job_status and execution_status are dropped
    # by the migrations that created them. If a later revision adds a native enum,
    # it must drop it here-style -- autogenerate never emits DROP TYPE, and the
    # *second* `upgrade head` is what fails.
